CREATE Table Ingredient(
	IngredientId INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Name TEXT NOT NULL,
	Calories INTEGER NOT NULL,
	Protein INTEGER NOT NULL,
	Sugar INTEGER NOT NULL,
	Unit TEXT NOT NULL
)